### ISSUE TITLE
Update for use with InvokeAi 4.x.x

### ISSUE THREAD

**Issue by angeloshredder** [VeyDlin/image-resize-plus-node#1]
Hi thanks for this great node, i was using it in lot of my workflows.
But when i upgraded to the latest invoke version 4.0.1, my workflows stoped to work because of lot of costume node, i have hard time to make them fonctional, 
and especially for this node, i missed all the links to inputs and outputs and it's hard to figure out which node was linked to the input of image-resioze-plus-node.

Can you please, if you can and have time, update this node and make it usable for 4.0.1 ?
Thanks

**Comment by VeyDlin** [comment]
Yes, I was going to update all my nodes in the coming days

**Comment by VeyDlin** [comment]
Done
